### PR TITLE
Update/merging new 3.17.2 commits

### PR DESCRIPTION
**Pull request by imashok02**
This contains new changes for 3.17.2 cocos2dx. Ios build needs this update to work, also verified with android

### CODE REVIEW

**Review by nasimafeef — APPROVED** [review]

**Comment by rampr** [comment]
Nice Ashok. How were our changes applied ?
Also, why did we stop at 3.17.2 ? Can we not use the latest codebase?

**Review by vyshnavsdeepak — APPROVED** [review]

**Comment by imashok02** [comment]
> Nice Ashok. How were our changes applied ?
> Also, why did we stop at 3.17.2 ? Can we not use the latest codebase?

**Comment by imashok02** [comment]
We are merging latest v3.17.2 commits to our existing hc-v3. Did this because we need an update for ios to build. It worked with this branch. I didnot try going above. My description mislead i guess, will update. These doesnot have our changes.

**Comment by rampr** [comment]
Looks like the changes are already there. Please clarify @imashok02 
https://github.com/cocos2d/cocos2d-x/compare/v3...hashcube:hc-v3

**Review by rampr — APPROVED** [review]

**Review by sameer-manek — APPROVED** [review]

**Pull request merged**
